In [1]:
import pandas as pd

In [2]:
dfresult_xq = pd.read_excel('sample_posts_20220324_1.xlsx', '600196_from_xueqiu', engine='openpyxl')

In [87]:
dfxq = pd.read_excel('xq_roberta_dianp_ratings.xlsx', engine = 'openpyxl')

In [89]:
dfxq.head(1)

,Unnamed: 0,ticker,ticker.1,post_id,url,title,description,text,clean_cmt,ratings
0,0,SH600196,复星医药,214820856,https://xueqiu.com/5210704716/214820856,如果经济发生滞胀，该如何保卫自己的财富？,毫不夸张地说，当下的经济情况，距离经济滞胀已经不远了。 如果不是相对宽松的货币政策，仍然在推...,毫不夸张地说，当下的经济情况，距离经济滞胀已经不远了。如果不是相对宽松的货币政策，仍然在推动...,毫不夸张地说当下的经济情况距离经济滞胀已经不远了如果不是相对宽松的货币政策仍然在推动着整体经...,"[{'label': 'negative (stars 1, 2 and 3)', 'sco..."

In [91]:
dianp = []
for i in range(len(dfxq)):
    if 'negative' in dfxq['ratings'][i]:
        s = 0
    else:
        s = 1
    dianp.append(s)
dfxq['dianp'] = dianp

In [92]:
dfresult_xq['dianp'] = dfxq['dianp'].head(110)

In [95]:
human_dianp = []
for i in range(len(dfresult_xq)):
    if dfresult_xq['score'][i] <= 3:
        a = 0
    else:
        a = 1
    human_dianp.append(a)

dfresult_xq['human_dianp'] = human_dianp

In [40]:
dfresult_xq = dfresult_xq.head(110)

In [25]:
import re
s = list(int(s) for s in re.findall(r'-?\d+\.?\d*', dfxq['ratings'][0][12:19]))

In [29]:
def convert(list):
      
    # Converting integer list to string list
    s = [str(i) for i in list]
      
    # Join list items using join()
    res = int("".join(s))
      
    return(res)

In [64]:
clean_dg = []
for i in range(len(dfxq.head(110))):
    s = list(int(s) for s in re.findall(r'-?\d+\.?\d*', dfxq['ratings'][i][12:19]))
    s = convert(s)
    clean_dg.append(s)

In [33]:
clean = []
for i in range(len(dfxq)):
    s = list(int(s) for s in re.findall(r'-?\d+\.?\d*', dfxq['ratings'][i][12:19]))
    s = convert(s)
    if s >= 4:
        result = 'positive'
    elif s == 3:
        result = 'neutral'
    else:
        result = 'negative'
    clean.append(result)

,ticker,ticker.1,post_id,url,title,description,text,score,human,model,human_score,model_score,model_star
0,SH600196,复星医药,214820856,https://xueqiu.com/5210704716/214820856,如果经济发生滞胀，该如何保卫自己的财富？,毫不夸张地说，当下的经济情况，距离经济滞胀已经不远了。 如果不是相对宽松的货币政策，仍然在推...,毫不夸张地说，当下的经济情况，距离经济滞胀已经不远了。如果不是相对宽松的货币政策，仍然在推动...,3.0,neutral,positive,1,2,5

In [78]:
clean_model_bi = []
for i in range(len(dfresult_xq)):
    s = int(dfresult_xq['model_star'][i])
    if s >= 3:
        result = 1
    else:
        result = 0
    clean_model_bi.append(result)
dfresult_xq['model_bi'] = clean_model_bi

In [79]:
clean_human_bi = []
for i in range(len(dfresult_xq)):
    s = int(dfresult_xq['score'][i])
    if s >= 3:
        result = 1
    else:
        result = 0
    clean_human_bi.append(result)
dfresult_xq['human_bi'] = clean_human_bi

In [80]:
dfresult_xq

,ticker,ticker.1,post_id,url,title,description,text,score,human,model,human_score,model_score,model_star,model_bi,human_bi
0,SH600196,复星医药,214820856,https://xueqiu.com/5210704716/214820856,如果经济发生滞胀，该如何保卫自己的财富？,毫不夸张地说，当下的经济情况，距离经济滞胀已经不远了。 如果不是相对宽松的货币政策，仍然在推...,毫不夸张地说，当下的经济情况，距离经济滞胀已经不远了。如果不是相对宽松的货币政策，仍然在推动...,3.0,neutral,positive,1,2,5,1,1
1,SH600196,复星医药,214779357,https://xueqiu.com/2714322037/214779357,NaN,股票交易终极的本质就是资本的趋利避害。$上海机场(SH600009)$ $长春高新(SZ00...,股票交易终极的本质就是资本的趋利避害。$上海机场(SH600009)$;$长春高新(SZ00...,3.0,neutral,positive,1,2,5,1,1
2,SH600196,复星医药,215082914,https://xueqiu.com/3235023571/215082914,NaN,$复星医药(SH600196)$ 盐野义也会是复星的，连中三元,$复星医药(SH600196)$;盐野义也会是复星的，连中三元,4.0,positive,positive,2,2,5,1,1
3,SH600196,复星医药,212474495,https://xueqiu.com/7972500030/212474495,NaN,复星医药会议记录：网页链接 复星医药上周宣布向香港捐赠价值1000万港币的抗疫物资，包括快速...,复星医药会议记录：网页链接复星医药上周宣布向香港捐赠价值1000万港币的抗疫物资，包括快速抗...,3.0,neutral,positive,1,2,5,1,1
4,SH600196,复星医药,214552997,https://xueqiu.com/6270575505/214552997,NaN,$复星医药(SH600196)$ 57.8亿。。。,$复星医药(SH600196)$;57.8亿。。。,3.0,neutral,positive,1,2,5,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,SH600196,复星医药,214843921,https://xueqiu.com/4429388114/214843921,NaN,$复星医药(SH600196)$ 再强调一句，让唱多的先买啊,$复星医药(SH600196)$;再强调一句，让唱多的先买啊,3.0,neutral,negative,1,0,2,0,1
106,SH600196,复星医药,214489288,https://xueqiu.com/9637282380/214489288,NaN,$复星医药(SH600196)$ $复星医药(02196)$ 恭喜复星医药先后获得默沙东和辉...,$复星医药(SH600196)$;$复星医药(02196)$ 恭喜复星医药先后获得默沙东和辉...,3.0,neutral,positive,1,2,5,1,1
107,SH600196,复星医药,214811887,https://xueqiu.com/4874546710/214811887,NaN,$复星医药(SH600196)$ 干得漂亮，一个亿。四个55，55。,$复星医药(SH600196)$;干得漂亮，一个亿。四个55，55。,4.0,positive,positive,2,2,5,1,1
108,SH600196,复星医药,214638661,https://xueqiu.com/3550432608/214638661,NaN,复星的股民也可以分享一下这份沃森的电话记录，可以这么说，沃森的利好也绝对是复星的利好，有些原...,复星的股民也可以分享一下这份沃森的电话记录，可以这么说，沃森的利好也绝对是复星的利好，有些原...,3.0,neutral,positive,1,2,5,1,1
109,SH600196,复星医药,214818170,https://xueqiu.com/1569069228/214818170,NaN,$复星医药(SH600196)$ $沃森生物(SZ300142)$ 复星这是要接棒中国医药的节奏？,$复星医药(SH600196)$;$沃森生物(SZ300142)$ 复星这是要接棒中国医药的节奏？,3.0,neutral,positive,1,2,5,1,1

In [35]:
dfxq['model_sentiment'] = clean

In [65]:
dfresult_xq['model_star'] = clean_dg

In [74]:
dfresult_xq.groupby('model_star').count()

,ticker,ticker.1,post_id,url,title,description,text,score,human,model,human_score,model_score
model_star,,,,,,,,,,,,
1,9,9,9,9,0,9,9,9,9,9,9,9
2,7,7,7,7,0,7,7,7,7,7,7,7
3,9,9,9,9,1,9,9,9,9,9,9,9
4,3,3,3,3,0,3,3,3,3,3,3,3
5,82,82,82,82,12,82,82,82,82,82,82,82

In [41]:
human = []
for i in range(len(dfresult_xq)):
    s = int(dfresult_xq['score'][i])
    if s >= 4:
        result = 'positive'
    elif s == 3:
        result = 'neutral'
    else:
        result = 'negative'
    human.append(result)

In [43]:
dfresult_xq['human'] = human

In [45]:
dfxq1 = dfxq.head(110)

In [48]:
dfresult_xq['model'] = dfxq1['model_sentiment']

In [61]:
dfresult_xq.head()

,ticker,ticker.1,post_id,url,title,description,text,score,human,model,human_score,model_score
0,SH600196,复星医药,214820856,https://xueqiu.com/5210704716/214820856,如果经济发生滞胀，该如何保卫自己的财富？,毫不夸张地说，当下的经济情况，距离经济滞胀已经不远了。 如果不是相对宽松的货币政策，仍然在推...,毫不夸张地说，当下的经济情况，距离经济滞胀已经不远了。如果不是相对宽松的货币政策，仍然在推动...,3.0,neutral,positive,1,2
1,SH600196,复星医药,214779357,https://xueqiu.com/2714322037/214779357,NaN,股票交易终极的本质就是资本的趋利避害。$上海机场(SH600009)$ $长春高新(SZ00...,股票交易终极的本质就是资本的趋利避害。$上海机场(SH600009)$;$长春高新(SZ00...,3.0,neutral,positive,1,2
2,SH600196,复星医药,215082914,https://xueqiu.com/3235023571/215082914,NaN,$复星医药(SH600196)$ 盐野义也会是复星的，连中三元,$复星医药(SH600196)$;盐野义也会是复星的，连中三元,4.0,positive,positive,2,2
3,SH600196,复星医药,212474495,https://xueqiu.com/7972500030/212474495,NaN,复星医药会议记录：网页链接 复星医药上周宣布向香港捐赠价值1000万港币的抗疫物资，包括快速...,复星医药会议记录：网页链接复星医药上周宣布向香港捐赠价值1000万港币的抗疫物资，包括快速抗...,3.0,neutral,positive,1,2
4,SH600196,复星医药,214552997,https://xueqiu.com/6270575505/214552997,NaN,$复星医药(SH600196)$ 57.8亿。。。,$复星医药(SH600196)$;57.8亿。。。,3.0,neutral,positive,1,2

In [53]:
humanlist = []
for i in range(len(dfresult_xq)):
    if dfresult_xq['human'][i] == 'positive':
        a = 2
    elif dfresult_xq['human'][i] == 'neutral':
        a = 1
    else:
        a = 0
    humanlist.append(a)
dfresult_xq['human_score'] = humanlist

modellist = []
for i in range(len(dfresult_xq)):
    if dfresult_xq['model'][i] == 'positive':
        a = 2
    elif dfresult_xq['model'][i] == 'neutral':
        a = 1
    else:
        a = 0
    modellist.append(a)
dfresult_xq['model_score'] = modellist

In [105]:
dfresult_xq.to_excel('xqsentiment_all.xlsx')

In [98]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
test = list(dfresult_xq['human_dianp'])
predict = list(dfresult_xq['dianp'])
accuracy = accuracy_score(test, predict)

In [99]:
accuracy

0.6

In [100]:
precision = precision_score(test, predict)
recall = recall_score(test, predict)
f1 = f1_score(test, predict)

In [101]:
print(accuracy)
print(precision)
print(recall)
print(f1)

0.6
0.2727272727272727
0.7894736842105263
0.4054054054054054

In [103]:
dfresult_xq.groupby('dianp').count()

,ticker,ticker.1,post_id,url,title,description,text,score,human,model,human_score,model_score,model_star,model_bi,human_bi,human_dianp
dianp,,,,,,,,,,,,,,,,
0,55,55,55,55,5,55,55,55,55,55,55,55,55,55,55,55
1,55,55,55,55,8,55,55,55,55,55,55,55,55,55,55,55